###### Markdown
- 마크다운 셀
  - 특수기호 한칸 띄어서 문서 작성
- 코드 셀
  - 1 + 3

- 셀 이동 
  - 화살표 위/ 아래 
- 수정 모드/커맨드 모드
  - Enter / Esc
- 실행
  - Ctrl or Shift or Alt + Enter
- 셀 만들기
  - 커맨드 모드에서 b 
- 셀 지우기
  - 커맨드 모드에서 x

In [10]:
a = "A"
b = 'B' #편하고 보기에도 간단하다
type(a), type(b), a, b ,'A' == "A"

(str, str, 'A', 'B', True)

In [17]:
a = 3
b = 3.14 #값을 할당할때 데이터 타입이 결정된다
type(a), type(b)

(int, float)

In [19]:
a = 5.14
a

5.14

In [23]:
#비교 연산자
1 > 0, 2<5, 3<=5,  4==4, 3 != 2

(True, True, True, True, True)

In [28]:
#논리 연산자 &&(and) ||(or)  !(not)  기존 기호는 없습니다
True and True, True or False, not True

(True, True, False)

In [31]:
#비트연산자는 있습니다
1 & 5, 1 | 5

(1, 5)

In [ ]:
# 파이썬은 {코드블록} 이 없습니다. :  들여쓰기 

In [56]:
# if , for 문에서는 print 필요
a = 10
if a % 2 == 1:
    print("a is odd") # 들여쓰기 4칸
elif a % 2 ==0:  
    print("a is even")
else:
    print("no")

a is even


삼항 연산자 없습니다
for(int i=0; i< 5 ; i++){    
    
}

In [59]:
for i in range(2):
    print(i)

0
1


In [60]:
#shift tab
for i in range(1, 10, 3):  # (start, end, step)
    print(i)

1
4
7


In [62]:
for i in range(10, 1, -3):  # (start, end, step)
    print(i)

10
7
4


In [67]:
#증감 연산자 ++ -- 가 없습니다, 중복이니까 없앴다.
a = 3
a += 1 
a

4

if else 와 같은 문법 switch case 없습니다. 중복이니까 없습니다

###### 자료 구조
  모든 종류의 데이터를 다 담을 수 있다
- 리스트 : [  ]  : 
- 튜플 : ( ) 추가, 수정, 제거 등이 안된다
- dict 딕셔너리 : {key:value, key:value,.....} 

- 배열 : 같은 종류의 데이터만 담는다 

In [73]:
l = [1,2,3,4, 'a', 'abc', [1,2,3]]
type(l), len(l), l

(list, 7, [1, 2, 3, 4, 'a', 'abc', [1, 2, 3]])

In [76]:
l.append(10)
l

[1, 2, 3, 4, 'a', 'abc', [1, 2, 3], 10, 10, 10]

In [78]:
t = (1,2,3,4)
type(t), t 

(tuple, (1, 2, 3, 4))

In [81]:
d = {'name': 'Park', 'age':20}
type(d), d

(dict, {'name': 'Park', 'age': 20})

In [85]:
# 조회, DataFrame 컬럼 조회 문법과 동일
d['age']

21

In [88]:
# 여러개의 키 조회
d.fromkeys(['age', 'name'])

{'age': None, 'name': None}

In [82]:
# 추가
d['city'] = 'Seoul'
d

{'name': 'Park', 'age': 20, 'city': 'Seoul'}

In [84]:
# 변경
d['age'] = 21
d

{'name': 'Park', 'age': 21, 'city': 'Seoul'}

함수 만들기
int add(int a, int b){
   return a + b
}

In [91]:
#def 함수 정의
def add(a, b):
   return a + b

In [92]:
add(5,5)

10

In [95]:
class Animal:
    name = '' # 클래스 변수
    def __init__(self): # 생성자, self 는 Java의 this (클래스 객체를 가리킵니다)
        print('생성자')
    
    def info(self):
        print('info')

In [100]:
#Animal a = new Animal();
a = Animal()
a.info()

생성자
info


# numpy 라이브러리
- numeric python
- 수치 데이터를 다루는 라이브러리
- 리스트나 튜플, 딕셔너리 등은 연산이 안됩니다
- scikit-learn, Tensorflow 와 데이터가 호환됩니다

In [ ]:
x[3:, -5:]  ?
x.reshape([-1, 5])  ?

In [102]:
a = [1,2,3] #리스트
b = [5,6,7]
type(a)

list

In [105]:
a + b # 연산이 안돼!

[1, 2, 3, 5, 6, 7]

In [106]:
import numpy as np

In [109]:
a = np.array(a) # 배열로 변환
b = np.array(b)
type(a), a #n(number) d(demension)

(numpy.ndarray, array([1, 2, 3]))

In [113]:
2 * a * a + b # 연산이 된다 

array([ 7, 14, 25])

In [115]:
? np.arange

In [120]:
a = np.arange(6).reshape((2,3)) # 2행 3열
a # C,Java, 파이썬은 행 우선 / Fortran, R 은 열 우선

array([[0, 1, 2],
       [3, 4, 5]])

In [130]:
# reshape 할때 -1 : unknown dimension 
a.reshape((6, 1, -1)) # 메모리 데이터는 1차원으로 저장되있어서 불변 
b = a.reshape((2,3)) # (행, 열) 은 인간의 해석, 컴퓨터에게는 모든 데이터는 1차원

In [134]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [138]:
#인덱싱 : (정수)인덱스로 데이터를 선택하는 것
#차원은 , 로 구분
b[0, 0], b[0, 1], b[1, 2], b[1, 1]

(0, 1, 5, 4)

In [143]:
#행 뽑기
b[1]

array([3, 4, 5])

In [147]:
#열 선택 [0,3] 만 선택하기
# : ALL 
b[:, 2]  

array([2, 5])

 시작:끝
 시작값을 생략하면 0
 끝값을 생략하면 끝까지

In [152]:
b[1:2] # 1행부터 2행 전까지

array([[3, 4, 5]])

In [153]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [156]:
# [1,2] [4,5] 만 뽑고싶다
b[:, 1:]

array([[1, 2],
       [4, 5]])

In [157]:
c = np.arange(1,10).reshape((3,3))
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [161]:
c[1,2], c[:2], c[1: ,:2]

(6, array([[1, 2, 3],
        [4, 5, 6]]), array([[4, 5],
        [7, 8]]))

# 6 만 선택
# (1,2,3,4,5,6) 만 선택
# (4,5,7,8) 만 선택

In [164]:
a = np.array([1,2,3]) # 요소 3개의 1차원 배열
a

array([1, 2, 3])

In [174]:
a = np.random.randint(0, 45, size=[5])
a

array([41, 18, 11, 35, 10])

In [176]:
a[-1] #뒤에서 첫번째 값 

10

In [179]:
a[-2: ] #뒤에서 두번째 값부터 : (끝까지)

array([35, 10])

In [180]:
a[:-2]  # (처음부터): 뒤에서 두번째 값 전까지

array([41, 18, 11])

In [181]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

###  3,6,9 를 인덱싱하세요 
###  5,6,8,9  를 - 인덱스를 이용해서 뽑아보세요

In [183]:
c[:,-1], c[-2:, -2:]

(array([3, 6, 9]), array([[5, 6],
        [8, 9]]))

### 축 axis

In [186]:
c.shape, np.ndim(c) # n : number, (행,열), (Y, X)

((3, 3), 2)

In [194]:
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [193]:
# 통계
np.sum(c), np.max(c), np.min(c), np.mean(c), np.std(c), np.median(c)

(45, 9, 1, 5.0, 2.581988897471611, 5.0)

In [196]:
np.sum(c, axis=0) 

array([12, 15, 18])

In [197]:
np.sum(c, axis=1) 

array([ 6, 15, 24])

In [201]:
np.argmax(c), np.argmin(c) # max, min 값의 위치 

(8, 0)

### 배열 붙이기 
- stack (쌓다) : 차원 1 증가
- concatenate (이어붙이다, 연쇄하다) : 차원 유지

In [206]:
? np.stack

In [205]:
np.concatenate((c,c,c), axis=1)

array([[1, 2, 3, 1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9, 7, 8, 9]])

In [215]:
np.stack((c,c), axis=2).shape

(3, 3, 2)

In [216]:
np.stack((c,c), axis=2)

array([[[1, 1],
        [2, 2],
        [3, 3]],

       [[4, 4],
        [5, 5],
        [6, 6]],

       [[7, 7],
        [8, 8],
        [9, 9]]])

### broadcasting : 서로 다른 모양의 배열끼리 연산이 가능해지도록
- 조건 : 축 길이가 같거나 한쪽이 1

In [230]:
c + np.array([0,10]) # (3,3) + (2) 

ValueError: operands could not be broadcast together with shapes (3,3) (2,) 

In [226]:
c + np.array([0,10,100]) # 2차원 + 1차원 

array([[  1,  12, 103],
       [  4,  15, 106],
       [  7,  18, 109]])

In [227]:
# reshape(( )), ([])
c + np.array([0,10,100]).reshape([3,1]) # 2차원(3,3) + 2차원(3,1)

array([[  1,   2,   3],
       [ 14,  15,  16],
       [107, 108, 109]])

### 2 반의 성적점수를 하나의 배열로 합친 후 각 반의 평균을 구하세요
#### 각 반의 1등 점수는? 
####  0반 [10,20,10,20] 
####  1반 [20,25,24,26]

답 :  평균 [x,x]

과정 : 배열로 만들어서 합치고 축별로 평균 구하기 

In [233]:
a = np.array([10,20,10,20])
b = np.array([20,25,24,26])
c = np.stack((a,b), axis=0)
c

array([[10, 20, 10, 20],
       [20, 25, 24, 26]])

In [236]:
np.mean(c, axis=1), np.argmax(np.mean(c, axis=1))

(array([15.  , 23.75]), 1)

머신러닝 : 사이킷럿 라이브러리 : 자동 (편하고 좋아)
딥러닝   : 텐서플로우 라이브러리: 수동 (불편해)    
           케라스 라이브러리 : 반자동 (편해)