# 분류
#### 클래스가 2종류일 때는 2진 분류(binary classification), 다중 multi classification

문제 : 예측 > 분류
예 : 과체중 예측하기, 과체중일 확률이 0.6, 반올림(0.6) = 1, 클래스=1
입력 : 몸무게와 키
출력 : 클래스(저체중 0, 정상 1, 과체중 2)
출력 : 클래스(사과0, 배1, 포도2) : LinearRegression 불가능

In [49]:
import numpy as np

In [50]:
x = [[48,180],[50,190],[55,160], [60,165], [65, 155], [70,180], [75,160]]
y = [0, 0, 1, 1, 2, 1, 2]
#선형함수 Y = WX + b,  X = [x1, x2], W = [w1, w2]
#Y_0 = W_0 X + b_0
#Y_1 = W_1 X + b_1
#Y_2 = W_2 X + b_2
# W = (3,2), b=(3,1)
# W = [w10 w20]
#     [w11 w21]
#     [w12 w22]

In [88]:
import pandas as pd
df = pd.read_csv('./datasets/wine.data', header=None)
df.shape
#첫번째 컬럼이 원산지 클래스

(178, 14)

In [90]:
df.isna().sum().sum()

0

In [106]:
y = df.iloc[:, 0]
x = df.iloc[:, 1:]
x.shape # W [3,13] b[3,1]

(178, 13)

In [108]:
x = np.array(x)
y = np.array(y)
from sklearn.linear_model import LinearRegression
model = LinearRegression().fit(x,y)
model.coef_, model.intercept_

(array([-0.1,  0. , -0.1,  0. , -0. ,  0.1, -0.4, -0.3,  0. ,  0.1, -0.1,
        -0.3, -0. ]), 4.47328530579772)

In [109]:
#예측 =  w1 * x1 + x2 * x2 + b
y_hat = np.sum(model.coef_ * x, axis=1) + model.intercept_
y_hat

array([0.8, 0.9, 1.1, 0.9, 1.6, 0.8, 0.8, 0.9, 1. , 1.1, 0.8, 1.1, 1. ,
       0.6, 0.6, 1.1, 1.1, 1.2, 0.6, 1.2, 1.1, 1.5, 0.8, 1.2, 1.2, 1.4,
       1. , 1.3, 1.1, 1.2, 1.2, 1. , 1.1, 1.1, 1.2, 1.3, 1.3, 1.4, 1.2,
       1.1, 1.3, 1.4, 0.8, 1.6, 1.3, 1.3, 1. , 1.1, 1.4, 1.1, 1.2, 0.9,
       0.9, 1. , 1.2, 1.5, 1.2, 1. , 1. , 2.4, 2.2, 2.5, 1.9, 1.9, 2.1,
       1.8, 1.6, 1.9, 2. , 2. , 2.2, 1.7, 2.1, 1.6, 1.9, 2.3, 2.1, 2.2,
       1.8, 1.9, 1.9, 1.6, 2.1, 2.4, 1.8, 1.8, 2.2, 2.1, 2. , 2. , 2.1,
       2.3, 2.2, 1.9, 2.1, 1.6, 2.4, 1.8, 1.5, 1.7, 1.8, 2. , 1.9, 2.4,
       1.7, 2. , 1.8, 2.1, 2.1, 1.5, 2.2, 2.1, 1.8, 2.3, 2. , 2. , 2. ,
       2. , 2.4, 2. , 1.7, 1.3, 2.1, 2. , 1.8, 1.9, 1.9, 2.3, 2.1, 2.2,
       2.5, 2.7, 2.9, 2.8, 2.7, 2.8, 2.8, 3.1, 2.7, 2.8, 2.5, 2.4, 2.6,
       2.6, 2.8, 2.6, 3. , 3. , 3. , 3. , 3. , 3.2, 3.2, 3. , 3. , 3.1,
       3. , 3. , 3.2, 3.2, 3.2, 2.6, 2.7, 2.6, 3. , 3. , 3.1, 3.1, 2.9,
       3. , 2.9, 3.2, 2.9, 2.8, 2.9, 3. , 2.9, 3.1])

In [114]:
np.round(y_hat)

array([1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 2., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 2., 2., 3., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2., 2.,
       2., 2., 1., 2., 2., 2., 2., 2., 2., 2., 2., 2., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 2., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3., 3.,
       3., 3., 3., 3., 3., 3., 3., 3.])

반올림은 미분이 안되기 때문에 경사하강법에서는 사용할 수 없습니다.
그래서 반올림과 성격이 유사하면서 미분이 되는 로지스틱함수(시그모이드)를 사용합니다

In [115]:
z = np.arange(-10,10,0.1)
sigmoid = 1/ (1+ np.exp(-z))

In [116]:
import matplotlib.pyplot as plt

In [117]:
from sklearn.linear_model import LogisticRegression
model = LogisticRegression().fit(x,y)
model.coef_, model.intercept_

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:469: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


(array([[-5.3e-01,  7.7e-01,  1.1e+00, -6.3e-01, -2.4e-02,  1.2e-01,
          1.4e+00,  9.2e-02, -4.4e-01, -1.1e-01, -1.7e-01,  8.5e-01,
          1.6e-02],
        [ 9.0e-01, -1.2e+00, -8.4e-01,  2.5e-01,  5.5e-03,  2.4e-01,
          5.8e-01,  4.2e-01,  7.0e-01, -1.8e+00,  9.1e-01,  2.0e-02,
         -1.3e-02],
        [-3.4e-01,  6.5e-01,  1.0e-01,  1.3e-01,  1.9e-02, -6.3e-01,
         -1.9e+00, -1.5e-01, -7.3e-01,  1.1e+00, -5.6e-01, -1.2e+00,
          1.2e-04]]), array([-0.3,  0.4, -0.1]))

In [118]:
model.coef_.shape, x.shape

((3, 13), (178, 13))

In [119]:
x

array([[1.4e+01, 1.7e+00, 2.4e+00, ..., 1.0e+00, 3.9e+00, 1.1e+03],
       [1.3e+01, 1.8e+00, 2.1e+00, ..., 1.1e+00, 3.4e+00, 1.0e+03],
       [1.3e+01, 2.4e+00, 2.7e+00, ..., 1.0e+00, 3.2e+00, 1.2e+03],
       ...,
       [1.3e+01, 4.3e+00, 2.3e+00, ..., 5.9e-01, 1.6e+00, 8.4e+02],
       [1.3e+01, 2.6e+00, 2.4e+00, ..., 6.0e-01, 1.6e+00, 8.4e+02],
       [1.4e+01, 4.1e+00, 2.7e+00, ..., 6.1e-01, 1.6e+00, 5.6e+02]])

In [120]:
model.predict(x) 

array([1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [126]:
# class Score 
np.set_printoptions(precision=1)
y_hat = np.matmul(model.coef_, x.T) + np.expand_dims(model.intercept_, axis=1)
y_hat.shape

(3, 178)

In [127]:
np.argmax(y_hat, axis=0) + 1 
#몇번째 행값이 가장 큰가 > 어떤 경작지에서 왔을 확률이 큰가 

array([1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

In [124]:
y

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3], dtype=int64)

## 예측 LinearRegression : Y = WX + b
## 분류 LogistRegression : Y = sigmoid(WX + b)
그러므로 분류는 예측을 먼저 하고 나서 분류하는 것입니다

(4,2) * (2,3) = (4,3)

In [150]:
a = np.arange(8).reshape(4,2)
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [151]:
w = np.arange(6).reshape(2,3)
w

array([[0, 1, 2],
       [3, 4, 5]])

In [152]:
np.matmul(a, w)

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33],
       [21, 34, 47]])